defaultContentLanguage: "en" # 默认语言为中文
languageCode: "en" #　使用中文
hasCJKLanguage: true # 启用对东亚文字的支持
title: "Jun's website" # 浏览器标签名
theme: "FixIt" # 主题
# permalinks:
#   posts: /posts/:year/:month/:day/
summaryLength: 180
params: # 覆盖默认选项
  defaultTheme: "auto" # FixIt 默认样式为 auto
  gitRepo: "https://github.com/kongjun18/blog" # 源代码 Github 网址
  externalIcon: true # 启用外链
  ibruce:
    enable: true
    enablePost: true
  header:
    title:
      name: "Jun's website" # 网址 header 标题
      logo: "/logo.svg"
  footer:
    license: '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
    since: 2022 # 网站创建时间
  page:
    math:
      enable: true
      type: "mathjax"
      mathjax:
        cdn: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
        packages:
          # '[+]': ['configmacros']
        macros:
          # "bold": ["{\\bf #1}", 1]   # usage: $\bold{math}$
        loader:
          load:
            - 'ui/safe'
          paths:
            # custom: "https://cdn.jsdelivr.net/gh/sonoisa/XyJax-v3@3.0.1/build/"
          # more loader config e.g source, dependencies, provides etc.
        options:
          enableMenu: true
          skipHtmlTags:
            - "script"
            - "noscript"
            - "style"
            - "textarea"
            - "pre"
            - "code"
            - "math"
            - "select"
            - "option"
            - "mjx-container"
          ignoreHtmlClass: "mathjax_ignore"
          includeHtmlTags:
            # "#comment": ""
            # br: "\n"
            # wbr: ""
    autoBookmark: true # 关闭页面时保存阅读进度
    gravatarForce: false
    code:
      maxShownLines: 40
    comment:
      enable: true
      giscus:
        enable: true
        repo: "kongjun18/kongjun18.github.io"
        repoId: "R_kgDOICeqmQ"
        category: "Announcements"
        categoryId: "DIC_kwDOICeqmc4CVeTb"
        mapping: "pathname"
        reactionsEnabled: "1"
        emitMetadata: "0"
        inputPosition: "top"
        lightTheme: "light"
        darkTheme: "dark_dimmed"
        lazyLoad: true
  tagcloud:
    enable: true
  author: # 作者信息，用于 archetypes 模版
    name: "Jun"
    link: "https://github.com/kongjun18"
    avatar: "/images/avatar.jpg"
  home:
    rss: 10
    profile:
      enable: true
      gravatarEmail: ""
      avatarURL: "/images/avatar.jpg" # 头像图片
      avatarMenu: "about"
      subtitle: "主题的晦涩 人生的短暂" # 头像下的文字
      typeit: true
  social:
    Github: "kongjun18"
    Email: "kongjun18@outlook.com"
  pangu:
    enable: true # 自动开启盘古插件
  githubCorner: # 在右上角显示博客 Github 链接
    enable: true
    permalink: "https://github.com/kongjun18/kongjun18.github.io"
    title: "Source Code of This Site"
    position: "left"

  search:
    enable: true
    # 搜索引擎的类型 ["lunr", "algolia", "fuse"]
    type: "fuse"
    # 文章内容最长索引长度
    contentLength: 4000
    # 搜索框的占位提示语
    placeholder: ""
    # FixIt 0.2.1 | 新增 最大结果数目
    maxResultLength: 10
    # FixIt 0.2.3 | 新增 结果内容片段长度
    snippetLength: 50
    # FixIt 0.2.1 | 新增 搜索结果中高亮部分的 HTML 标签
    highlightTag: "em"
    # FixIt 0.2.4 | 新增 是否在搜索索引中使用基于 baseURL 的绝对路径
    absoluteURL: false
    fuse:
      # FixIt 0.2.17 | 新增 https://fusejs.io/api/options.html
      isCaseSensitive: false
      minMatchCharLength: 2
      findAllMatches: false
      location: 0
      threshold: 0.3
      distance: 100
      ignoreLocation: false
      useExtendedSearch: false
      ignoreFieldNorm: false
      markup:
goldmark:
  extensions:
    passthrough:
      enable: true
      delimiters:
        block:
          - ['\[', '\]']
          - ['$$', '$$']
        inline:
          - ['\(', '\)']
          - ['$', '$']
menu:
  main:
    - identifier: "posts"
      pre: ""
      post: ""
      name: "Posts"
      url: "/posts/"
      title: ""
      weight: 1
    - identifier: "categories"
      pre: ""
      post: ""
      name: "Categories"
      url: "/categories/"
      title: ""
      weight: 2
    - identifier: "tags"
      pre: ""
      post: ""
      name: "Tags"
      url: "/tags/"
      title: ""
      weight: 3
    # - identifier: "archives"
    #   pre: ""
    #   post: ""
    #   name: "Archives"
    #   url: "/archives/"
    #   title: ""
    #   weight: 4
    - identifier: "about"
      pre: ""
      post: ""
      name: "About"
      url: "/about/"
      title: ""
      weight: 5
markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 4
    startLevel: 2
outputs:
  home: ["HTML", "RSS", "JSON"]
